updated reward system per request
PiusLim373/drone_control pull request #4
Opened 2024-10-09 10:25 UTC by AnsonCheah

2024-10-09 10:25 UTC, AnsonCheah commented
LGTM!!!!!

2024-10-10 02:02 UTC, PiusLim373 requested changes

2024-10-10 02:02 UTC, PiusLim373 commented on .vscode/settings.json
plese dont push the .vscode folder

2024-10-10 02:02 UTC, PiusLim373 commented on drone_control_gym.py
> +        ic(self.last_imu_gyro_data)
too much logging

2024-10-10 02:02 UTC, PiusLim373 commented on drone_control_gym.py
> +        ic(self.imu_gyro_data)
too much logging

2024-10-10 02:02 UTC, PiusLim373 commented on drone_control_gym.py
> +        self.imu_acc_data = self.drone.sensordata[self.imu_acc_start : self.imu_acc_start + 3]  # Accelerometer (x, y, z)
can we fix the naming convention? eg: self.drone_acc and self.drone_gyro

2024-10-10 02:02 UTC, PiusLim373 commented on drone_control_gym.py
> +        return (self.reward, self.has_finished, self.goal_attributes, self.drone_rpy, self.last_drone_motor_thrust, self.drone_motor_thrust, self.last_imu_acc_data, self.imu_acc_data, self.last_imu_g
why is this return a tuple? does the learning agent need the last motor thrust, last acc and last gyro data?

2024-10-10 02:02 UTC, PiusLim373 commented on drone_control_gym.py
> +        return (self.reward, self.has_finished, self.goal_attributes, self.drone_rpy, self.last_drone_motor_thrust, self.drone_motor_thrust, self.last_imu_acc_data, self.imu_acc_data, self.last_imu_g
why is this return a tuple? does the learning agent need the last motor thrust, last acc and last gyro data?

2024-10-11 10:03 UTC, PiusLim373 approved these changes

2024-10-11 10:03 UTC, merged